Encode the output to UTF-8 before writing to file
Having run pyScss with `--watch`, it died with:
```
  File "/usr/local/lib/python2.7/dist-packages/scss/tool.py", line 254, in compile
    dest_file.write(self.css.compile(scss_file=src_path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\uf0d7' in position 816: ordinal not in range(128)
```
Encoding to UTF-8, assuming that's what everyone wants, before writing the file, solves it.